version: "3.4"
services:
  strapi:
    build: .
    ports:
      - 1337:1337
  postgres:
      image: postgres:11-alpine
      shm_size: 8g
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "5434:5432"
      volumes:
        - /data/sigmaverse-postgres:/var/lib/postgresql/data:rw
