version: "3.4"
networks:
  strapi:
    external: true
services:
  strapi:
    build: .
    ports:
      - 1337:1337
    networks:
      - strapi
    depends_on:
      - postgres-cms
  postgres-cms:
    image: postgres:11-alpine
    networks:
     - strapi
    shm_size: 8g
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ~/data/sigmaverse-postgres:/var/lib/postgresql/data:rw
